name: app_group_directory
description: >-
  Retrieve App Group directory on iOS.
  Port of FileManager.containerURL to Flutter.
version: 2.1.0
homepage: https://github.com/Albert221/app_group_directory

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AppGroupDirectoryPlugin
