name: app_group_directory
description: >-
  Retrieve App Group directory on iOS.
  Port of FileManager.containerURL to Flutter.
version: 2.0.0
homepage: https://github.com/Albert221/app_group_directory

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AppGroupDirectoryPlugin
